provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  # ... other provider config ...

functions:
  api:
    handler: src.api.handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: "*"
          cors:
            allowedOrigins:
              - "https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3--5173--d20a0a75.local-credentialless.webcontainer-api.io"
              - "http://localhost:5173" # For local development
              # Add your production domain when ready
            allowedHeaders:
              - "Content-Type"
              - "Authorization"
              - "X-Api-Key"
              - "X-Amz-Date"
              - "X-Amz-Security-Token"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: true
            maxAge: 3600 # Cache preflight requests for 1 hour
