name: CD

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: SAM build
        run: sam build

      - name: Deploy to dev
        if: github.event.inputs.environment == 'dev' || github.event.inputs.environment == null
        run: |
          sam deploy \
            --config-env dev \
            --parameter-overrides \
              Stage=dev \
              AdminApiKey=${{ secrets.ADMIN_API_KEY }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset

      - name: Deploy to prod
        if: github.event.inputs.environment == 'prod'
        run: |
          sam deploy \
            --config-env prod \
            --parameter-overrides \
              Stage=prod \
              AdminApiKey=${{ secrets.ADMIN_API_KEY }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
